name: reminder_app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  bloc: ^9.2.0
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_gen: ^5.12.0
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.2.3
  fpdart: ^1.2.0
  freezed_annotation: ^3.1.0
  get_it: ^9.2.0
  go_router: ^17.0.1
  injectable: ^2.7.1+4
  json_annotation: ^4.9.0

dev_dependencies:
  build_runner: ^2.10.5
  flutter_gen_runner: ^5.12.0
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.2.4
  injectable_generator: ^2.12.0
  json_serializable: ^6.11.4

flutter:
  uses-material-design: true
